rule[
 ruleID "r5: 6-ring formation_rev"
 left[
  node[id 6 label "H+"]
  node[id 9 label "H"]
  edge[source 0 target 1 label "-"]
  edge[source 1 target 2 label "="]
  edge[source 2 target 3 label "-"]
  edge[source 3 target 8 label "="]
  edge[source 8 target 9 label "-"]
 ]
 context[
  node[id 0 label "N"]
  node[id 1 label "C"]
  node[id 2 label "N"]
  node[id 3 label "C"]
  node[id 4 label "C"]
  node[id 5 label "C"]
  node[id 7 label "*"]
  node[id 8 label "N"]
  node[id 10 label "*"]
  edge[source 0 target 5 label "-"]
  edge[source 0 target 7 label "-"]
  edge[source 1 target 10 label "-"]
  edge[source 3 target 4 label "-"]
  edge[source 4 target 5 label "="]
 ]
 right[
  node[id 6 label "H"]
  node[id 9 label "H+"]
  edge[source 0 target 6 label "-"]
  edge[source 1 target 2 label "#"]
  edge[source 3 target 8 label "#"]
 ]
]

